### ISSUE TITLE
How reliable is vpic API?

### ISSUE THREAD

**Issue by seperman** [davidpeckham/vpic-api#7]
Hi David,
Thanks for the vpic client.
I was looking at vpic's FAQ, and they say they can handle `During the normal week, we can easily handle between 1000 – 2000 transactions/minute on the servers.`. That seems very low and makes me wonder if using their API is a bad idea.
You must have had a lot of experience with their API. Can you chime in?
Thanks!

**Comment by davidpeckham** [comment]
Hi Sep,They do enforce limits on API usage, so you’re better off using their Microsoft SQL Server database download if you can.I use the API for ad box requests. For higher volume I use my own client-side rate limiter. DavidOn Dec 19, 2023, at 1:46 PM, Sep Dehpour ***@***.***> wrote:﻿
Hi David,
Thanks for the vpic client.
I was looking at vpic's FAQ, and they say they can handle During the normal week, we can easily handle between 1000 – 2000 transactions/minute on the servers.. That seems very low and makes me wonder if using their API is a bad idea.
You must have had a lot of experience with their API. Can you chime in?
Thanks!

**Comment by seperman** [comment]
Cool, thanks!
